services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile  # 修正為正確的路徑
    container_name: todo_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    command: uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000

  db:
    image: postgres:14
    container_name: todo_db
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
